name: Fix Styling

on:
  push:
    branches:
    - master
    - "*.x"
    paths:
    - "**.php"
  pull_request:
    paths:
    - "**.php"

permissions:
  contents: write

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        extensions: dom, libxml, mbstring, tokenizer, xml
        coverage: none

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php8.4-cs-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php8.4-cs-composer-

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Execute PHP CS Fixer
      run: composer cs-fix

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Fix styling
        skip_dirty_check: true
